In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Scikit-learn datasets and tools
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression, RidgeCV, LassoCV
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

In [2]:
data= load_diabetes(as_frame=True)

In [8]:
df=data.frame

In [ ]:
df[]

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0
...,...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207,178.0
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485,104.0
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491,132.0
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930,220.0
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064,57.0

In [10]:
X_df = data.data.copy()
y = data.target.copy()

In [18]:
df = X_df.copy()
df["target"] = y

In [19]:
df.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0

In [20]:
y

0      151.0
1       75.0
2      141.0
3      206.0
4      135.0
       ...
437    178.0
438    104.0
439    132.0
440    220.0
441     57.0
Name: target, Length: 442, dtype: float64

In [21]:
X_df

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641
...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

In [22]:
x_train, x_test, y_train,y_test = train_test_split(X_df,y, test_size=0.2 ,random_state=42)

In [24]:
mean_guess= y_train.mean()
mean_guess

np.float64(153.73654390934846)

In [25]:
baseline_predictios= np.full(shape=y_test.shape,fill_value=mean_guess)

In [26]:
baseline_predictios

array([153.73654391, 153.73654391, 153.73654391, 153.73654391,
       153.73654391, 153.73654391, 153.73654391, 153.73654391,
       153.73654391, 153.73654391, 153.73654391, 153.73654391,
       153.73654391, 153.73654391, 153.73654391, 153.73654391,
       153.73654391, 153.73654391, 153.73654391, 153.73654391,
       153.73654391, 153.73654391, 153.73654391, 153.73654391,
       153.73654391, 153.73654391, 153.73654391, 153.73654391,
       153.73654391, 153.73654391, 153.73654391, 153.73654391,
       153.73654391, 153.73654391, 153.73654391, 153.73654391,
       153.73654391, 153.73654391, 153.73654391, 153.73654391,
       153.73654391, 153.73654391, 153.73654391, 153.73654391,
       153.73654391, 153.73654391, 153.73654391, 153.73654391,
       153.73654391, 153.73654391, 153.73654391, 153.73654391,
       153.73654391, 153.73654391, 153.73654391, 153.73654391,
       153.73654391, 153.73654391, 153.73654391, 153.73654391,
       153.73654391, 153.73654391, 153.73654391, 153.73654391,
       153.73654391, 153.73654391, 153.73654391, 153.73654391,
       153.73654391, 153.73654391, 153.73654391, 153.73654391,
       153.73654391, 153.73654391, 153.73654391, 153.73654391,
       153.73654391, 153.73654391, 153.73654391, 153.73654391,
       153.73654391, 153.73654391, 153.73654391, 153.73654391,
       153.73654391, 153.73654391, 153.73654391, 153.73654391,
       153.73654391])

In [35]:
baseline_mae= mean_absolute_error(y_test,baseline_predictios )
baseline_mae

64.00646146990485

In [27]:
lin_reg= LinearRegression()

In [28]:
lin_reg.fit(x_train,y_train)

LinearRegression()

In [29]:
y_pred= lin_reg.predict(x_test)

In [31]:
mae= mean_absolute_error(y_test, y_pred)
rsme= mean_squared_error(y_test,y_pred)
r2score= r2_score(y_test,y_pred)

In [33]:
mae,rsme,r2score

(42.79409467959994, 2900.1936284934804, 0.4526027629719196)

In [36]:
alphas= np.logspace(-4,4,100)

In [37]:
alphas

array([1.00000000e-04, 1.20450354e-04, 1.45082878e-04, 1.74752840e-04,
       2.10490414e-04, 2.53536449e-04, 3.05385551e-04, 3.67837977e-04,
       4.43062146e-04, 5.33669923e-04, 6.42807312e-04, 7.74263683e-04,
       9.32603347e-04, 1.12332403e-03, 1.35304777e-03, 1.62975083e-03,
       1.96304065e-03, 2.36448941e-03, 2.84803587e-03, 3.43046929e-03,
       4.13201240e-03, 4.97702356e-03, 5.99484250e-03, 7.22080902e-03,
       8.69749003e-03, 1.04761575e-02, 1.26185688e-02, 1.51991108e-02,
       1.83073828e-02, 2.20513074e-02, 2.65608778e-02, 3.19926714e-02,
       3.85352859e-02, 4.64158883e-02, 5.59081018e-02, 6.73415066e-02,
       8.11130831e-02, 9.77009957e-02, 1.17681195e-01, 1.41747416e-01,
       1.70735265e-01, 2.05651231e-01, 2.47707636e-01, 2.98364724e-01,
       3.59381366e-01, 4.32876128e-01, 5.21400829e-01, 6.28029144e-01,
       7.56463328e-01, 9.11162756e-01, 1.09749877e+00, 1.32194115e+00,
       1.59228279e+00, 1.91791026e+00, 2.31012970e+00, 2.78255940e+00,
       3.35160265e+00, 4.03701726e+00, 4.86260158e+00, 5.85702082e+00,
       7.05480231e+00, 8.49753436e+00, 1.02353102e+01, 1.23284674e+01,
       1.48496826e+01, 1.78864953e+01, 2.15443469e+01, 2.59502421e+01,
       3.12571585e+01, 3.76493581e+01, 4.53487851e+01, 5.46227722e+01,
       6.57933225e+01, 7.92482898e+01, 9.54548457e+01, 1.14975700e+02,
       1.38488637e+02, 1.66810054e+02, 2.00923300e+02, 2.42012826e+02,
       2.91505306e+02, 3.51119173e+02, 4.22924287e+02, 5.09413801e+02,
       6.13590727e+02, 7.39072203e+02, 8.90215085e+02, 1.07226722e+03,
       1.29154967e+03, 1.55567614e+03, 1.87381742e+03, 2.25701972e+03,
       2.71858824e+03, 3.27454916e+03, 3.94420606e+03, 4.75081016e+03,
       5.72236766e+03, 6.89261210e+03, 8.30217568e+03, 1.00000000e+04])

In [39]:
ridge_model = Pipeline([
("scaler",StandardScaler()),
("ridge",RidgeCV(alphas=alphas, cv=5))


])

lasso_model = Pipeline([
    ("scaler", StandardScaler()),
    ("lasso", LassoCV(alphas=alphas, cv=5, max_iter=20000))
])

In [41]:
ridge_model.fit(x_train, y_train)
lasso_model.fit(x_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('lasso',
                 LassoCV(alphas=array([1.00000000e-04, 1.20450354e-04, 1.45082878e-04, 1.74752840e-04,
       2.10490414e-04, 2.53536449e-04, 3.05385551e-04, 3.67837977e-04,
       4.43062146e-04, 5.33669923e-04, 6.42807312e-04, 7.74263683e-04,
       9.32603347e-04, 1.12332403e-03, 1.35304777e-03, 1.62975083e-03,
       1.96304065e-03, 2.36448941e-03, 2.848...
       1.38488637e+02, 1.66810054e+02, 2.00923300e+02, 2.42012826e+02,
       2.91505306e+02, 3.51119173e+02, 4.22924287e+02, 5.09413801e+02,
       6.13590727e+02, 7.39072203e+02, 8.90215085e+02, 1.07226722e+03,
       1.29154967e+03, 1.55567614e+03, 1.87381742e+03, 2.25701972e+03,
       2.71858824e+03, 3.27454916e+03, 3.94420606e+03, 4.75081016e+03,
       5.72236766e+03, 6.89261210e+03, 8.30217568e+03, 1.00000000e+04]),
                         cv=5, max_iter=20000))])

In [42]:
lasso_weights = lasso_model.named_steps["lasso"].coef_
zero_weights_count = sum(abs(lasso_weights) < 1e-7)

In [44]:
zero_weights_count

np.int64(3)